### ISSUE TITLE
GATK installation

### ISSUE THREAD

**Issue by tanyasarkjain** [ucb-rit/savio-training-parallel-2020#1]
Hi,
The guide is very useful for understanding parrallization of GATK however how do I install GATK --> it does not seem to be a preinstalled module and further research https://gatk.broadinstitute.org/hc/en-us/articles/360046877112-GATK-on-local-HPC-infrastructure shows that reqs such as mySQL are needed.
Thanks!

**Comment by paciorek** [comment]
We do have GATK already installed. 

See [these instructions](https://docs-research-it.berkeley.edu/services/high-performance-computing/getting-help/) for getting access to bioinformatics software in general, and then run `module avail gatk` to see the versions available.

For further questions on this, please follow [these instructions](https://docs-research-it.berkeley.edu/services/high-performance-computing/getting-help/). We don't generally handle questions via GitHub issues in our training materials.
